version: '2.0'
services:
  udagram-user-api:
    build:
      context: ../../udagram-user-api
      dockerfile: Dockerfile
    image: karoldavid/udagram-user-api
  udagram-feed-api:
    build:
      context: ../../udagram-feed-api
      dockerfile: Dockerfile
    image: karoldavid/udagram-feed-api
  reverseproxy:
    build:
      context: .
    image: karoldavid/udagram-reverse-proxy
  udagram-frontend:
    build:
      context: ../../udagram-frontend  
    image: karoldavid/udagram-frontend