apiVersion: v1
kind: Service
metadata:
  name: udagram-user-api
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-user-api
  labels:
    service: udagram-user-api
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: udagram-user-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
