apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api-svc
  selfLink: /api/v1/namespaces/default/services/udagram-feed-api-svc
  labels:
    service: udagram-feed-api
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-feed-api
